---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: dov-bear-deploy
  labels:
    name: dov-bear-deploy
  namespace: myns
spec:
  replicas: 3
  selector:
    matchLabels:
      name: dov-bear-po
      dept: dev
  template:
    metadata:
      name: dov-bear-po
      labels:
        name: dov-bear-po
        dept: dev
    spec:
      containers:
      - name: dov-bear-container
        image: chukmunnlee/dov-bear-golang@sha256:ec9c01eabd2e2bd78e75b1dfdeb228da1cf9f3ddc9e62d9d091ee8d73c342a34
        imagePullPolicy: IfNotPresent
        env:
        - name: INSTANCE_NAME
          value: dov-bear
        - name: INSTANCE_HASH
          valueFrom: 
            fieldRef:
              fieldPath: status.podIP
        - name: PORT 
          value: "3000"
        ports:
        - containerPort: 3000
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000